baseurl = "https://danglingpointers.com/"
languageCode = "en-us"
title = "Dangling Pointers"
disqusshortname = "danglingpointers"
preservetaxonomynames = true
pygmentscodefences = true
pygmentsuseclasses = true