baseurl = "http://danglingpointers.com/"
languageCode = "en-us"
title = "Dangling Pointers"
disqusshortname = "danglingpointers"
preservetaxonomynames = false
pygmentscodefences = true
pygmentsuseclasses = true